= eXtended Objects
Dirk Mahler <dirk.mahler@buschmais.com>

This document describes the core concepts of eXtended Objects.

:numbered!:
[abstract]
= Introduction

Modeling data objects for datastores (i.e. databases) in various domains often requires common properties
(e.g. lastChangedBy, created, name, etc.) to be present in several data types. This is commonly solved by defining
abstract base types representing a specific aspect or role and defining these properties here. Concrete data types may
derive from these base types if the information is needed. This approach comes to its limits if more than one aspect
shall be re-used in one POJO as multiple inheritance is not supported for classes in the Java language.

eXtended Objects (XO) allows modeling types as interfaces by specifying the required accessor methods
(i.e. getter and setter) and composing these types either statically or dynamically. The XO API uses well-known
concepts from existing persistence APIs (e.g. JPA, JDO) but extends them with functionality which is enabled by using
interfaces to define the data objects, e.g. type migration at runtime.
The XO implementation itself is datastore-agnostic, i.e. it does not depend on specific datastore concepts like
relational or graph databases, document stores etc. but allows using them. Datastore specific implementations can be
provided by implementing the SPI (Service Provider Interface), the reference implementation is based on the
graph database Neo4j.

= Core Concepts
== Static vs. Dynamic Composition

An example from a well known domain shall be used to explain the difference between both concepts of composition:

Person.java
[source,java]
----
public interface Person {
  String getName();
  void setName();
}
----

Actor.java
[source,java]
----
public interface Actor extends Person {
  List<Movie> getActedIn();
}
----

Director.java
[source,java]
----
public interface Director extends Person {
  List<Movie> getDirected();
}
----

Movie.java
[source,java]
----
public interface Movie {
  String getTitle();
  void setTitle();

  Director getDirectedBy();
  void setDirectedBy(Director directedBy);

  List<Actors> getActors();
}
----

Using the XO API the following use case can be implemented:

RaidersOfTheLostArk.java
[source,java]
----
public class RaidersOfTheLostArk {

  public static void main(String[] args) {
    // Bootstrap XO, a file META-INF/xo.xml is expected on the classpath
    XOManagerFactory xmf = XO.createXOManagerFactory("movies");

    // Obtain a XOManager (i.e. a connection to the datastore)
    XOManager xm = xmf.createXOManager();

    // Begin a transaction
    xm.currentTransaction.begin();

    // Create a data object representing an actor
    Actor harrison = xm.create(Actor.class);
    harrison.setName("Harrison Ford");

    // Create a data object representing a director
    Directory steven = xm.create(Director.class);
    steven.setName("Steven Spielberg");

    // Create a data object representing a movie
    Movie raiders = xm.create(Movie.class);
    raiders.setTitle("Raiders Of The Lost Ark");

    // Set the relations between all the created data objects
    raiders.setDirectedBy(steven);
    raiders.getActors().add(harrison);

    // Commit the transaction
    xm.currentTransaction.commit();

    // Close the XOManager
    xm.close();

    // Close the XOManagerFactory (on shutdown of the application)
    xmf.close();
  }
}
----

The types Actor and Director use static composition by extending from the type Person. But what happens if a person
works in both roles: actor and director? A new type extending from both would be required if static composition was used:

DirectingActor.java
[source,java]
----
public interface DirectingActor extends Director, Actor {
}
----

The situation gets even more complex if other roles (like screenwriter, editor, etc.) are added to the domain model.
Each combination of roles must be represented by such a type. Dynamic composition helps getting around this problem:

TempleOfDoom.java
[source,java]
----
public class TempleOfDoom {

  public static void main(String[] args) {
    XOManagerFactory xmf = XO.createXOManagerFactory("movies");
    XOManager xm = xmf.createXOManager();
    xm.currentTransaction.begin();
    Actor harrison = xm.create(Actor.class);
    harrison.setName("Harrison Ford");

    // Create Steven as composite object using more than one role
    CompositeObject steven = xm.create(Director.class, Actor.class);

    // Use Steven in the role of an actor
    steven.as(Actor.class).setName("Steven Spielberg");

    Movie temple = xm.create(Movie.class);
    temple.setTitle("Temple Of Doom");

    // Use Steven in the role of a director as the "director" property of the type Movie requires it
    temple.setDirectedBy(steven.as(Director.class));
    temple.getActors().add(harrison);

    // Steven also acted in "Temple Of Doom" (according to IMDB...)
    temple.getActors().add(steven.as(Actor.class));
    xm.currentTransaction.commit();
    xmf.close();
  }
}
----

== Runtime Entity Migration

There may be situations where an existing data object needs to be migrated to also represent other types. Using the
above example the fact that the director also acted in the movie might have been discovered after the data object
has been created using the type Director. XO offers a way to perform a migration at runtime and allows adding (or
removing) roles (i.e. types):

TempleOfDoom.java
[source,java]
----
public class TempleOfDoom {

  public static void main(String[] args) {
    XOManagerFactory xmf = XO.createXOManagerFactory("movies");
    XOManager xm = xmf.createXOManager();
    xm.currentTransaction.begin();

    // Create Steven as a director
    Director steven = xm.create(Director.class);
    steven.setName("Steven Spielberg");

    Movie temple = xm.create(Movie.class);
    temple.setTitle("Temple Of Doom");
    temple.setDirectedBy(steven);
    xm.currentTransaction.commit();

    // Some days later a fan discovers that Steven also acted in Temple Of Doom
    xm.currentTransaction.begin();
    CompositeObject multiTalentedSteven = xm.migrate(steven, Director.class, Actor.class);
    temple.getActors().add(multiTalentedSteven.as(Actor.class));

    xm.currentTransaction.commit();
    xmf.close();
  }
}
----

= Available Datastore implementations

- Neo4j
- Titan
- Tinkerpop Blueprints
- OrientDb

= Neo4j Datastore
== Introduction

As a graph database Neo4j provides very powerful capabilities to store and query highly interconnected data structures
consisting of nodes and relationships between them. With release 2.0 the concept of labels has been introduced. One or
more labels can be added to a single node:

[source]
----
create
  (a:Person:Actor)
set
  a.name="Harrison Ford"
----

Using labels it is possible to write comprehensive queries using Cypher:

[source]
----
match
  (a:Person)
where
  a.name="Harrison Ford"
return
  a.name;
----

If a node has a label it can be assumed that it represents some type of data which requires the presence of specific
properties and relationships (e.g. property "name" for persons, "ACTED_IN" relations to movies). This implies that a
Neo4j label can be represented as a Java interface and vice versa.

Person.java
[source,java]
----
@Label("Person") // The value "Person" can be omitted, in this case the class name is used
public interface Person {
  String getName();
  void setName();
}
----

ActedIn.java
[source,java]
----
/**
* Qualifier to be used for bi-directional relations.
*/
@Relation("ACTED_IN")
@Retention(RUNTIME)
public @interface ActedIn {
}
----

Actor.java
[source,java]
----
@Label("Actor")
public interface Actor extends Person {
  @ActedIn
  @Outgoing
  List<Movie> getActedIn();
}
----

Director.java
[source,java]
----
@Label("Director")
public interface Director extends Person {

  @Relation("DIRECTED")
  @Outgoing
  List<Movie> getDirected();
}
----

Movie.java
[source,java]
----
@Label("Movie")
public interface Movie {
  String getTitle();
  void setTitle();

  @Relation("DIRECTED")
  @Incoming
  Director getDirectedBy();
  void setDirectedBy(Director directedBy);

  @ActedIn
  @Incoming
  List<Actors> getActors();
}
----

== Maven Dependencies
The Neo4j datastore for eXtended Objects is available from Maven Central and can be specified as dependency in pom.xml files:

pom.xml
[source,xml]
----
<project ...>
    ...

    <properties>
        <com.buschmais.xo_version>0.3.0</com.buschmais.xo_version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.buschmais.xo</groupId>
            <artifactId>xo.neo4j</artifactId>
            <version>${com.buschmais.xo_version}</version>
        </dependency>
    </dependencies>

    ...
</project>
----

= Titan Datastore

https://github.com/PureSolTechnologies/extended-objects-titan

= TinkerPop Blueprints Datastore

https://github.com/BluWings/xo-tinkerpop-blueprints

= OrientDb Datastore

https://github.com/BluWings/xo-orientdb

= API Overview

eXtended Objects provides an API which re-uses concepts of other frameworks and standards like JPA or JDO:

XOUnit::
  A configuration defining a datastore configuration, the managed entity and relation types and several settings
  like validation and concurrency management. Can either be defined as XML descriptor by providing a concrete instance.
XOManagerFactory::
  Factory for XOManager instances which is configured using a XOUnit.
XOManager::
  Represents an active session with the datastore, provides
  - operations to create, find, delete entities or relations
  - a query factory
  - access to the associated XOTransation object.
XOTransaction::
  Allows control of datastore transactions if supported by the underlying datastore.
Query::
  Allows the execution of user defined queries.


